name: ci

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.2
          - 7.3
          - 7.4
        prefer-lowest: [false]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 13306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extension: pdo, pdo_mysql, mbstring #optional, setup extensions
          coverage: none #optional, setup coverage driver
          pecl: false #optional, setup PECL

      - name: Check Version
        run: |
          php -v
          php -m
          composer -V

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies (composer.lock)
        if: false == matrix.prefer-lowest
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install dependencies (prefer-lowest)
        if: true == matrix.prefer-lowest
        run: composer update --prefer-dist --no-progress --no-suggest --prefer-lowest

      - name: Run test suite
        run: composer exec -- phpunit -v
        env:
          TESTS_DB_MYSQL_HOST: 127.0.0.1
          TESTS_DB_MYSQL_PORT: 13306
          TESTS_DB_MYSQL_USERNAME: root
          TESTS_DB_MYSQL_PASSWORD: password
          TESTS_DB_MYSQL_DATABASE: testing